/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [BookingId]
      ,[VehicleNumber]
      ,[VehicleModel]
      ,[ServiceType]
      ,[ServiceInstructions]
      ,[ServiceTasks]
      ,[RequestedDate]
      ,[CompletedDate]
  FROM [ASMT].[dbo].[Services]